apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoservice
  labels:
    app: demoservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demoservice
  template:
    metadata:
      labels:
        app: demoservice
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        runAsNonRoot: true
      containers:
        - name: demoservice
          command: ["node", "app.js"]
          image: magalix/demoservice:v0.0.2
          env:
            - name: PORT
              value: "5000"
          ports:
            - containerPort: 5000
              name: liveness-port
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000

