---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: demoservice
  namespace: dev
spec:
  host: demoservice-svc
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
  - name: baseline
    labels:
      version: demoservice-baseline
  - name: routea
    labels:
      version: demoservice-routea