version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: KubeGuard
          command: |
            curl -sX POST \
                --data-binary "@./clean/deployment.yml" \
                -H "Content-Type: application/octet-stream" \
                -o res.json \
                $URL
            echo -e "\n===KubeGuard===\n"
            jq 'if .violations then .violations  else "No Violations" end' res.json
            jq -e '[select(.has_violations == false)] | any' > /dev/null res.json
 
